extends Node

var negative_action_pool: Array[Action] = [Action.new("Stole candies from a kid", 10),
                                Action.new("Selfish", 10),
                                Action.new("Didn't take care of his family", 50),
                                Action.new("Racist", 100),
                                Action.new("Shaked hand after toilets without hand cleaning", 20),
                                Action.new("Cheated on partner", 50),
                                Action.new("Abandonned a pet", 100),
                                Action.new("Lied frequently", 15),
                                Action.new("Drove being drunk", 80),
                                Action.new("Never said thank you", 15),
                                Action.new("Abandonned a child", 80),
                                Action.new("Speaked loudly on public transports", 25),
                                Action.new("Scammed a Kickstarter project", 30),
                                Action.new("Robbed a bank", 50),
                                Action.new("Payed employees below minimum wage", 50),
                                Action.new("Started a forest fire", 70),
                                Action.new("Didn't say hello during an interview", 5),
                                Action.new("Interrupted people constantly", 10),
                                Action.new("Often bragging about a new car", 10),
                                Action.new("Threw waste in a public park", 30),   
]

var positive_action_pool: Array[Action] = [Action.new("Gave money to charity", 30),
                                Action.new("Bought local food", 15),
                                Action.new("Ended a World War", 200),
                                Action.new("Volunteer for a humanitarian association", 60),
                                Action.new("Regular blood donator", 50),
                                Action.new("Returned lost wallet without taking the money", 30),
                                Action.new("Saved a duck's life by accident", 35),
                                Action.new("Saved lives everyday", 100),
                                Action.new("Helped a grandma to cross the street", 10),
                                Action.new("Protected younger against bullies at school", 35),
                                Action.new("Adopted an orphan", 70),
                                Action.new("Developed a cure for cancers", 300),
                                Action.new("Helped a stranger to find a job", 15),
                                Action.new("Helped a foreign tourist to find its way in the city", 20),
                                Action.new("Donates organs after death", 80),
                                Action.new("Organized neighbor parties", 30),
                                Action.new("Developed video games", 20),
                                Action.new("Donated hairs for cancer patients", 35),
                                Action.new("Brought a lost cat to the veterinarian", 40),
                                Action.new("Translated books for free", 20),
                                Action.new("Teaching disadvantadged children", 50),
                                Action.new("Helped rebuild homes after a natural disaster", 80),
                                Action.new("Left a bus sit for a pregnant person", 10),
                                Action.new("Helped a turtle cross the road", 5),
                                Action.new("Funded education for poor children", 70),
                                Action.new("Saved someone from drowning", 150),
                                Action.new("Helped a friend move apartments", 20),
                                ]

var neutral_action_pool: Array[Action] = [Action.new("Good at tennis", 0),
                                        Action.new("Loves pineapple on pizza", 0),
                                        Action.new("Happy when it's raining", 0),
                                        Action.new("Always has a pen on the ear", 0)]

var deadly_actions_pool: Array[Action] = [Action.new("Friend of god", 999, "heaven"),
                      Action.new("Guardian angel", 999, "heaven"),
                      Action.new("Established world peace", 999, "heaven"),
                      Action.new("Sacrificed own soul to save another", 999, "heaven"),
                      Action.new("Brought extinct species back to life", 999, "heaven"),
                      Action.new("Tried to kill god", 999, "hell"),
                      Action.new("Created a weapon to destroy the world", 999, "hell"),
                      Action.new("Murdered humans", 999, "hell"),
                      Action.new("Eradicated an animal species", 999, "hell"),
                      Action.new("Started a World War", 999, "hell"),]
